---
title: "Bird Community Metrics"
output: 
  github_document:
    df_print: tibble
---

```{r setup, message = FALSE}
library(tidyverse)
library(neonstore)
library(lubridate)
```


```{r  message = FALSE}
brd_countdata <- neonstore::neon_read("brd_countdata-expanded", col_types = vroom::cols(.default = "c"))
```

richness by month across all sites

```{r}
 brd_countdata %>%
  mutate(date = as.Date.POSIXct(startDate, "%Y-%m-%d")) %>% 
  mutate(month = format(date, "%Y-%m")) %>% 
  mutate(month = as.Date(paste(month, "01", sep="-"))) %>%
  select(scientificName, month, siteID) %>% 
  distinct() %>%
  count(month) %>% 
  ggplot(aes(month, n)) + geom_line() + geom_point()
```


```{r}
richness <- brd_countdata %>%
  mutate(year = lubridate::year(startDate)) %>%
  select(scientificName, year, siteID) %>% 
  distinct() %>%
  count(siteID, year)
richness
```

## Let's make a forecast:

```{r}
forecast <- richness %>% group_by(siteID) %>% summarize(forecast = mean(n), sd = sd(n))
readr::write_csv(forecast, "bird_richness.csv")

```