---
title: "Macroinvert Abundance Estimates"
output: 
  github_document:
    df_print: tibble
---

```{r setup, message = FALSE}
library(tidyverse)
library(neonstore)
library(lubridate)
```

<https://data.neonscience.org/data-products/DP1.20120.001>

```{r message = FALSE}
# neonstore::neon_download("DP1.20120.001")
# neonstore::neon_store("DP1.20120.001")
inv <- neonstore::neon_read("inv_taxonomyRaw-expanded")
sites <- neonstore::neon_sites() %>% select(siteID = siteCode, domainCode, domainName)

```

```{r}
inv_ts <- inv %>% 
  select(collectDate, siteID, scientificName, individualCount) %>%
  mutate(month = format(collectDate, "%Y-%m")) %>% 
  mutate(month = as.Date(paste(month, "01", sep="-"))) %>%
  group_by(scientificName, month, siteID) %>%
  summarize(count = sum(individualCount)) %>%
  ungroup()
```



Total counts:

```{r}
inv_ts %>% group_by(month) %>% summarize(count = sum(count, na.rm = TRUE)) %>%
  ggplot(aes(month, count)) + geom_line() + geom_point()
```
```{r fig.height=10}
inv_ts %>% 
  left_join(sites) %>% 
  group_by(month, domainName) %>% 
  summarize(count = sum(count, na.rm = TRUE)) %>%
  ggplot(aes(month, count)) + geom_line() + geom_point() + 
  facet_wrap(~domainName, ncol = 3, scales="free_y")
```




----




Let's just consider the 4 most common species and the 4 sites for that have
the most individual entries (sample months) for those species


```{r}
top_sp <- zoo_ts %>% count(scientificName, sort=TRUE) %>% pull(scientificName) %>% head(4)
top_sites <- zoo_ts %>% filter(scientificName %in% top_sp)  %>% count(siteID, sort=TRUE) %>% pull(siteID) %>% head(4)
```

We really ought to estimate abundance by accounting for detection probability.  

Observing raw counts directly, we see: 


```{r}
zoo_ts %>% filter(scientificName %in% top_sp, siteID %in% top_sites) %>% 
  ggplot(aes(month, count)) +
  geom_line() + geom_point() + 
  facet_grid(scientificName ~ siteID, scales = "free_y")
```